# Generated by Django 3.1.3 on 2020-11-11 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='opponent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Person_2', to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='chats',
            name='user_1',
        ),
        migrations.AddField(
            model_name='chats',
            name='user_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Person_1', to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Baned_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_baned', models.BooleanField(default=False, verbose_name='Baned_user')),
                ('reason', models.CharField(blank=True, max_length=250, verbose_name='related on bans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
        ),
    ]
